[build]
  command = "npm install && npm run build" # Or "npm install" if no other build steps
  publish = "." # Assuming your index.html is at the root for deployment

[functions]
  directory = "functions" # IMPORTANT: Points to the new folder

[[plugins]]
package = "@netlify/plugin-functions-install-core"
