[build]
  command = "cd functions && npm install && cd .. && npm run build" # Adjust 'npm run build' to your actual build command
  publish = "your-publish-directory" # e.g., "dist" or "build"

[functions]
  directory = "functions"
[[plugins]]
package = "@netlify/plugin-functions-install-core"
